import React from 'react';

export const meta = {
  id: "lane-drone",
  title: "Lane Following Drone",
  category: "Robotics",
  date: "May 15, 2019",
  image: "/vcard-personal-portfolio/assets/images/lane_following_drone_1774990581879.png",
  description: "An autonomous airborne drone built from scratch using ROS, Gazebo, and a Deep Learning CNN for lane detection."
};

export default function Post() {
  return (
    <div className="blog-text" style={{ color: "var(--light-gray)", lineHeight: 1.6 }}>
      <p>In early 2019, I undertook an ambitious project to build an autonomous lane-following drone from the ground up. This involved not only the physical construction and wiring of the custom drone hardware, but also the development of a sophisticated software stack for autonomous navigation.</p>
      <br />
      <p>I developed the software interfaces using <strong>ROS</strong> and <strong>Gazebo</strong>, connecting them with MavROS to communicate directly with the drone's flight controllers. At the core of the drone's perception system, I implemented a robust ROS node featuring a Convolutional Neural Network (CNN) based lane detector, trained using Deep Learning techniques to identify aerial paths.</p>
      <br />
      <p>To tie it all together, I engineered the flight control systems allowing the vehicle to dynamically change its course and velocity based on the real-time lane predictions generated by the neural network. This project successfully demonstrated the integration of complex deep learning models into airborne robotic control loops.</p>
    </div>
  );
}
